# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: CopyFiles@2
  inputs:
    sourceFolder: 'build/libs'
    contents: '**/*'
    targetFolder: $(Build.ArtifactStagingDirectory)/libs
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'libs'
    pathtoPublish: $(Build.ArtifactStagingDirectory)/libs
- task: GithubRelease@0
  inputs:
    gitHubConnection: victoryforphil
    repositoryName: VictoryConnect-ClientJS
    action: 'create' # Options: create, edit, discard
    target: '$(build.sourceVersion)' # Required when action == create || action == edit
    tagSource: 'auto' # Required when action == create. Options: auto, manual
    tag: '$(build.sourceVersion)' # Required when action == edit || action == discard || tagSource == manual
    #title: # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    #releaseNotes: # Optional
    assets: '$(build.artifactStagingDirectory)/libs' # Optional
    #assetUploadMode: 'delete' # Optional. Options: delete, replace
    #isDraft: false # Optional
    #isPreRelease: false # Optional
    #addChangeLog: true # Optional